---
development:
  cloud_name: hhfwkirsy
  api_key: '742287613718166'
  api_secret: ebHjgEnxs8KQ3YpGQCJBeB17JO0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hhfwkirsy
  api_key: '742287613718166'
  api_secret: ebHjgEnxs8KQ3YpGQCJBeB17JO0
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hhfwkirsy
  api_key: '742287613718166'
  api_secret: ebHjgEnxs8KQ3YpGQCJBeB17JO0
  enhance_image_tag: true
  static_image_support: false
